{% set name = "plotmol" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/plotmol/archive/{{ version }}.tar.gz
  sha256: 2d083ddc1bffd5cee257c0d55336add6afe8ef8cc9748d7ead4fa3efc95151eb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioneer
    # needed for dynamic version, as setuptools will try
    # and import the package when installing to determine it
    # and so needs to be able to find the dependencies
    - rdkit
    - bokeh >=3
  run:
    - python >=3.10
    - rdkit
    - bokeh >=3
test:
  imports:
    - plotmol

about:
  home: https://github.com/SimonBoothroyd/plotmol
  summary: 'Interactive plotting of data annotated with molecule structures.'
  description: |
    A framework that provides a set of functionalities for creating interactive plots that are 
    annotated with molecular structures using the bokeh library.
  license: MIT
  license_file:
    - LICENSE
  doc_url: https://github.com/SimonBoothroyd/plotmol
  dev_url: https://github.com/SimonBoothroyd/plotmol

extra:
  recipe-maintainers:
    - SimonBoothroyd
